spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: zull-gateway

server:
  port: 30002


zuul:
  routes:
    sample:
      path: /secure/user**
      #url: http://34.95.224.180:8087/secure/user
      #url: http://localhost:8087/secure/user
      service-id: API-SERVICE
      roles: user,master
      strip-prefix: false
    master:
      path: /secure/master/**
      #url: http://34.95.224.180:8087/secure/master
      #url: http://localhost:8087/secure/master
      service-id: API-SERVICE
      roles: master
      strip-prefix: false
    logout:
      path: /logout
      url: http://nowhere
      roles: user,master
      strip-prefix: false
    open:
      path: /open/**
      #url: http://34.95.224.180:8087/open
      #url: http://localhost:8087/open
      service-id: API-SERVICE
      strip-prefix: false

keycloak:
  # turn off keycloak spring boot auto-configuration:
  # We only want to use Spring Security without servlet container specific infrastructure
  # This allows us to pull the Keycloak configuration from here instead of keycloak.json
  enabled: false

  #  realm: bootadmin
  #  auth-server-url: http://localhost:8180/auth
  #  # The client_id
  #  resource: app-todo
  #  credentials:
  #    # The client_secret
  #    secret: 2cc653a3-24cc-4241-896d-813a726f9b33
  #  ssl-required: external
  #  autodetect-bearer-only: true
  #  # Configures what principal.getName() will return
  #  principal-attribute: preferred_username
  #  use-resource-role-mappings: true
  #  token-minimum-time-to-live: 30

  auth-server-url: http://cef07.hitss.com.br/auth
  public-client: false
  realm: api-gateway
  resource: service-user
  ssl-required: none
  credentials:
    secret: '123456'

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    serviceUrl:
      #defaultZone: ${EUREKA_URI:http://34.95.224.180:8761/eureka}
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
  ribbon:
    eureka:
      enabled: true
    http:
      client:
        enabled: true


logging:
  level:
    org:
      keycloak=TRACE: